version: '3.8'

services:
  grobid:
    build: .
    container_name: grobid
    ports:
      - "8070:8070"
  # fastchat:
  #   runtime: nvidia
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  #   build: ./FastChat
  #   container_name: FastChat
  #   ports:
  #     - "8030:8030"
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    tty: true
  frontend:
    build: ./frontend
    container_name: frontend
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/
      
