version: '3.8'

services:
  grobid:
    build: .
    container_name: grobid
    ports:
      - "8070:8070"
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
      - "8030:8030"
    volumes:
      - ./backend:/backend
    tty: true
  frontend:
    build: ./frontend
    container_name: frontend
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/
      
